---
name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 17

      - name: Install dependencies
        run: npm install

      - name: Check for linting errors
        run: npm run lint

      - name: Build production website
        run: npm run build
